---
title: "Charlotte_modeling"
author: "Charlotte Abrams"
output: github_document
---

```{r, message = FALSE}
library(tidyverse)
library(caret)
library(modelr)
library(glmnet)
library(pls)
```

```{r}
heart = readr::read_csv("data/train_imputed.csv") %>%
  mutate(pure_population = as.factor(pure_population),
         urban_influence = factor(urban_influence),
         economic_typology = as.factor(economic_typology),
         metro_adjacency = as.factor(metro_adjacency),
         metro = as.factor(metro)) 

x <- model.matrix(heart_disease_mortality_per_100k ~ ., data = heart)[,-1]
y <- heart$heart_disease_mortality_per_100k
```

Set up `caret` training control. 

```{r}
set.seed(2)
ctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 5)
```

## Lasso

Cross validate to find the optimal lambda value.

```{r}
set.seed(2)

lasso_fit <- train(heart_disease_mortality_per_100k ~ ., 
                   data = heart,
                   method = "glmnet",
                   tuneGrid = expand.grid(alpha = 1,
                                          lambda = exp(seq(-10, 0, length = 200))),
                   metric = "RMSE",
                   #preProcess = c("zv"),
                   trControl = ctrl)


plot(lasso_fit, xTrans = function(x) log(x)) #in correct range

best_lambda_lasso = lasso_fit$bestTune$lambda # lower lambda bc adjusted bounds

##centered, scaled coefficients from caret
predict(lasso_fit$finalModel, s = best_lambda_lasso, type = "coefficients") %>% 
  broom::tidy() %>% 
  arrange(desc(abs(value))) %>% 
  top_n(10)

predict(lasso_fit$finalModel, s = best_lambda_lasso, type = "coefficients") %>% 
  dim()

#saving caret object to rdata
saveRDS(lasso_fit, "lasso_imputed.rds")
```


## PCR

```{r, echo = T, message = FALSE, results='hide', warning=FALSE}
library(pdp)
#library(earth)
#library(vip)
#library(patchwork)

set.seed(2)
pcr_fit <- train(heart_disease_mortality_per_100k ~ ., 
                 data = heart,
                 method = "pcr",
                 trControl = ctrl,
                 metric = "RMSE",
                 tuneLength = 200)

plot(pcr_fit, xTrans = function(x) log(x)) 

pred_pcr <- predict(pcr_fit, ncomp = 35)


#saving caret object to rdata
saveRDS(pcr_fit, "pcr_imputed.rds")

#save(pcr_fit, file = 'pcr.RData')
#Calculate accuracy with MSE
#MSE = mean((pred_pcr - y)^2)
#print(MSE)

```






