---
title: "laura eda"
author: "Laura Cosgrove"
date: "3/26/2019"
output: github_document
---

```{r}
library(tidyverse)
library(ggjoy)
```

## Organizing factors:

```{r}
heart <- read_csv("./data/train.csv")
```

```{r, fig.width=10}
heart %>% 
  ggplot(aes(x = heart_disease_mortality_per_100k, y = metro, height=..density..)) +
  geom_joy(scale = 0.85)

heart %>% 
  ggplot(aes(x = heart_disease_mortality_per_100k, y = population, fill = metro, height=..density..)) +
  geom_joy(scale = 0.85)
```

Bimodal distribution for "urban population of 20,000 or more"

```{r}
heart <- heart %>% 
  mutate(population = factor(population, levels = c(
    "Counties in metro areas of 1 million population or more", 
    "Counties in metro areas of 250,000 to 1 million population", 
    "Counties in metro areas of fewer than 250,000 population", 
    "Urban population of 20,000 or more, adjacent to a metro area", 
    "Urban population of 20,000 or more, not adjacent to a metro area", 
    "Urban population of 2,500 to 19,999, adjacent to a metro area", 
    "Urban population of 2,500 to 19,999, not adjacent to a metro area", 
    "Completely rural or less than 2,500 urban population, adjacent to a metro area", 
    "Completely rural or less than 2,500 urban population, not adjacent to a metro area"),
    labels = c("Metro > 1 million", "Metro 250k - 1 million", "Metro <250k", "Urban >20,000 metro-adjacent", "Urban >20,000 metro non-adjacent","Urban 2,500-19,999 metro-adjacent", "Urban 2,500-19,999 metro non-adjacent", "Rural metro-adjacent", "Rural metro non-adjacent")),
    metro = factor(metro, levels = c("Metro", "Nonmetro")),
    area__urban_influence = factor(area__urban_influence, levels = c(
      "Large-in a metro area with at least 1 million residents or more", 
      "Small-in a metro area with fewer than 1 million residents",
      "Micropolitan adjacent to a large metro area",
      "Noncore adjacent to a large metro area",
      "Micropolitan adjacent to a small metro area",
      "Noncore adjacent to a small metro with town of at least 2,500 residents",
      "Noncore adjacent to a small metro and does not contain a town of at least 2,500 residents",
      "Micropolitan not adjacent to a metro area",
      "Noncore adjacent to micro area and contains a town of 2,500-19,999 residents",
      "Noncore adjacent to micro area and does not contain a town of at least 2,500 residents",
      "Noncore not adjacent to a metro/micro area and contains a town of 2,500  or more residents",
      "Noncore not adjacent to a metro/micro area and does not contain a town of at least 2,500 residents"),
      labels = 1:12)) %>% 
  mutate(area__urban_influence = fct_rev(area__urban_influence)) %>% 
  rename(metro_ruccs = metro, 
         population_ruccs = population,
         urban_influence = area__urban_influence)

heart %>% 
  ggplot(aes(y = heart_disease_mortality_per_100k, x = population_ruccs, fill = metro_ruccs)) +
  geom_boxplot() +
  coord_flip()

heart %>% 
  ggplot(aes(y = heart_disease_mortality_per_100k, x = urban_influence, fill = metro_ruccs)) +
  geom_boxplot() +
  coord_flip()

heart <- heart %>% 
  rename(economic_typology = econ__economic_typology) %>% 
  mutate(economic_typology = factor(economic_typology),
         economic_typology = fct_inorder(economic_typology)) 

heart %>% 
  ggplot(aes(y = heart_disease_mortality_per_100k, x = economic_typology, fill = metro_ruccs)) +
  geom_boxplot() +
  coord_flip()

```

Not a huge consistent effect for these area and economic typologies.

